### ISSUE TITLE
Handle file name of the TOSCA input in a robust way (i.e. remove the hard-coded filename constraint)

### ISSUE THREAD

**Issue by tzok** [indigo-dc/APIServerDaemon#38]
* Component: fgAPIServer & APIServerDaemon
* Version: v0.0.8
* Steps to reproduce:
  1. Add an application to fgAPIServer which is of ToscaIDC type and has a TOSCA template input named anything but `template.yml` (e.g. `template.yaml` or `tosca_template.yml`)
  2. Submit a task of this application type
* Actual behaviour: The task ends up in ABORTED state quickly and without any details about the reason of that outcome. In the logs, one may find that the TOSCA template was empty. Further reading the logs, one can finally find out that the APIServerDaemon looks for a hard-coded file name of `template.yml`.
* Expected behaviour: The fgAPIServer & APIServerDaemon must have a more robust solution to know the name of TOSCA template. Here are some ideas:
  1. Since ToscaIDC is a special application type, let it have a special input file type - the TOSCA template. User can name it anyhow, but upon creation of the application by the fgAPIServer, it will be consistently named or marked so that the problem never appears again.
  2. If that is not possible, then fgAPIServer should report an error during `POST` call for application adding/changing. The error will be issued if an application of ToscaIDC type does not have a `template.yml` input file.

**Comment by ricsxn** [comment]
Could you please verify if this is due to a configuration problem?
There are no hardcoded entries and template and parameter file name are configured during application installation. You can check these filenames (what ToscaIDC will expect) in the DB table infrastructure_parameter.

**Comment by tzok** [comment]
I confirm this was due to configuration issue... I was not aware that entry in `infrastructure_parameter` must match one of the input files, although it is logical. Thanks for clarification
